### PR TITLE
Pubkey.find_program_address()

### LINKED ISSUE #41: Support for find_program_address
[This](https://docs.rs/solana-program/latest/solana_program/pubkey/struct.Pubkey.html#method.find_program_address) function.

Would be nice to add it as a new way to add account validation.

### PR DESCRIPTION
**Pull request by orvioconge**
I think it's all there. Thought this would be harder to add but I was able to copy-paste my way to victory.

I just added the functionality as directly as I could, copying Solana's existing API. Not sure if that's what was wanted or not, but we can have a discussion now that the PR is here.

Closes #41

### CODE REVIEW

**Comment by mcintyre94** [comment]
Nice, looks good! Couple of minor things:

- Can you add this as a static function to `class Pubkey` in [the prelude python file](https://github.com/ameliatastic/seahorse-lang/blob/main/data/seahorse_prelude.py)? That's what editors use to do autocomplete/documentation for Seahorse built-ins

- More of a discussion point but we could possibly make `program_id` optional, defaulting to the current program ID. I'm not sure if we have any example of compiler code that is program ID aware, but in theory the compiler should know it from the `declare_id` call. Might be a rabbit hole and need a big change, might be pretty easy to do.

**Comment by orvioconge** [comment]
> More of a discussion point but we could possibly make program_id optional, defaulting to the current program ID.

I like the idea. Would be nice to offer more interesting support as opposed to just doing whatever the original API does, at least - I think this could work. As a side note, it actually might be necessary to add this because if people want to use their own program's ID, I think there's no native Seahorse way to even get that now.

I believe the ID from declare_id becomes available under a constant named `ID`, need to check.

I'll hold off on adding it to prelude.py until we figure out exactly what the API looks like (so I don't need to commit twice).

cc @ameliatastic

**Comment by ameliatastic** [comment]
"Use this program's id by default" sounds good! Looking into it, I think you just need to add a new use statement to the top of each source file in order to expose the program id.

**Comment by mcintyre94** [comment]
Oh hey TIL you can just do `id()` in Anchor to print the program ID. So I guess we could just render to that in Rust. Eg. https://beta.solpg.io/63765db877ea7f12846aef33

**Comment by orvioconge** [comment]
Oh yeah lol. Working on it.

**Comment by orvioconge** [comment]
Solved merge conflicts, I think it's all there. For reference, `print(Pubkey.find_program_address(['hello'])[0])` compiled to

```rs
solana_program::msg!(
    "{:?}",
    Pubkey::find_program_address(
        Mutable::new(vec!["hello".as_bytes().as_ref()])
            .borrow()
            .as_slice(),
        &id()
    )
    .0
);
```

which looks good to me.

**Pull request merged**
