### PR TITLE
Class methods

### PR DESCRIPTION
**Pull request by ameliatastic**
Adds methods (instance and static) for struct-type classes (a.k.a., non-enums). Accounts may not define constructors, since Solana needs to know they exist instead of just existing transiently in memory.

Example usage:

```py
class Point:
    x: i32
    y: i32

    # Constructor defined like in Python
    # Caveat: structs now derive `Default`, and have all of their fields set to
    # their default values
    def __init__(self, x: i32, y: i32):
        self.x = x
        self.y = y

    # Giving a method a `self` parameter makes it an instance method
    def manhattan_dist(self) -> i32:
        return self.x + self.y

    # No self = static method - no @staticmethod needed
    def origin() -> Point:
        return Point(0, 0)

# ...

@instruction
def ix(...):
    p = Point(2, 3)
    q = Point.origin()

    print(p.manhattan_dist(), q.manhattan_dist())
```

### CODE REVIEW

**Comment by mcintyre94** [comment]
Nice, this is an awesome addition, makes it feel much more like writing Python!

One question though, what would happen if there were multiple classes defining a `def origin()` static method for example?

In normal Python you'd write `q = Point.origin()` which would distinguish them, but here it looks like the static methods are ending up in the global scope?

**Comment by ameliatastic** [comment]
> Nice, this is an awesome addition, makes it feel much more like writing Python!
> 
> One question though, what would happen if there were multiple classes defining a `def origin()` static method for example?
> 
> In normal Python you'd write `q = Point.origin()` which would distinguish them, but here it looks like the static methods are ending up in the global scope?

Good catch, that was actually just a typo. It is just like Python, the call should have been `Point.origin()`.

**Comment by mcintyre94** [comment]
Ah cool, nice! I'd lean toward leaving `@staticmethod` off for now, it makes the code simpler (for both us and users of seahorse) and is very easy for someone to fix if they copy a chunk of python in and get the error. If people report that incompatibility as an annoyance maybe we can add it as being allowed but a no-op? But I think it's a good call to just skip it for now!

**Comment by ameliatastic** [comment]
sounds like a solid plan, ty for the input

**Pull request merged**
